### ISSUE TITLE
port to 1.21.3

### ISSUE THREAD

**Issue by himynameiscool782** [srnyx/limitless-lag#1]
### What and How?

port to 1.21.3

### Why?

just because my paper server runs on it

### Are there alternatives?

no not really

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by srnyx** [comment]
Should already support it, does it not work?

**Comment by himynameiscool782** [comment]
Sorry I apologize tuns out it does work although it seems as though I can't lag other players out only myself and when I unlag my self it doesnt unlag

________________________________

**Comment by srnyx** [comment]
> I can't lag other players out only myself

What happens when you try to use the command on someone else? What's sent in chat? Are you sure it isn't working?

> when I unlag my self it doesnt unlag

Same as above, what's sent in chat when you run the command? And what happens if you run it again, does it say it disabled it again or that i re-enabled?

**Comment by himynameiscool782** [comment]
I think it fixed itself sorry for wasting your time

________________________________

**Comment by srnyx** [comment]
> I think it fixed itself sorry for wasting your time

you're good! glad it figured itself out 😄
